import { Button, GridBox, LineEdit } from "std-widgets.slint";

component Calculator inherits Rectangle {
    callback send-carac(string);

    in-out property <string> input_value <=> input.text;
    in property <string> placeholder_value;
    in property <[string]> Calculator_buttons: [
        "7",
        "8",
        "9",
        "/",
        "4",
        "5",
        "6",
        "*",
        "1",
        "2",
        "3",
        "-",
        "0",
        ".",
        "=",
        "+"
    ];

    VerticalLayout {
        cross-axis-alignment: center;
        padding-top: 15px;
        spacing: 20px;

        input := LineEdit {
            width: parent.width - 50px;
            height: 40px;
            font-size: 20px;
            placeholder-text: root.placeholder_value != "" ? root.placeholder_value : "0";
        }

        GridLayout {
            width: parent.width - 50px;
            spacing: 5px;

            for button[i] in Calculator_buttons: Button {
                width: 50px;
                height: 35px;
                text: button;
                row: floor(i / 4);
                col: mod(i, 4);

                clicked => {
                    root.send-carac(button)
                }
            }

            Button {
                width: 50px;
                height: 35px;
                text: "C";
                row: 0;
                col: 5;

                clicked => {
                    root.send-carac("C")
                }
            }

            Button {
                width: 50px;
                height: 35px;
                text: "<-";
                row: 1;
                col: 5;

                clicked => {
                    root.send-carac("<-")
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    callback send-carac(string);

    in-out property <string> input_value <=> calc.input_value;
    in-out property <string> placeholder_value <=> calc.placeholder_value;

    width: 326px;
    height: 326px;

    calc := Calculator {
        send-carac(value) => { root.send-carac(value) }
    }
}
