import { Button, GridBox } from "std-widgets.slint";

struct ButtonData {
    value: string,
}

component Calculator inherits Rectangle {
    callback add-number(value: string);
    in property <string> input_value: "0";
    in property <[string]> Calculator_buttons: [
        "7",
        "8",
        "9",
        "/",
        "4",
        "5",
        "6",
        "*",
        "1",
        "2",
        "3",
        "-",
        "0",
        ".",
        "-/+",
        "+"
    ];

    VerticalLayout {
        cross-axis-alignment: center;
        padding-top: 15px;
        spacing: 20px;

        Rectangle {
            width: parent.width - 50px;
            height: 40px;
            background: white;
            clip: true;

            TextInput {
                text: input_value.is-empty ? "0" : input_value;
                read-only: true;
                color: black;
                width: max(parent.width, self.preferred-width);
                vertical-alignment: center;

                private property <length> margin: 1rem;
                cursor-position-changed(cursor-position) => {
                    if cursor-position.x + self.x < margin {
                        self.x = - cursor-position.x + margin;
                    } else if cursor-position.x + self.x > parent.width - margin - self.text-cursor-width {
                        self.x = parent.width - cursor-position.x - margin - self.text-cursor-width;
                    }
                }
            }
        }

        GridLayout {
            width: parent.width - 50px;
            spacing: 5px;

            for button[i] in Calculator_buttons: Button {
                width: 50px;
                height: 35px;
                text: button;
                row: floor(i / 4);
                col: mod(i, 4);

                clicked => {
                    root.add-number(button)
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    callback add-number(value: string);
    in property <string> input_value: "";

    width: 326px;
    height: 326px;

    Calculator {
        add-number(value) => { root.add-number(value) }
        input_value: root.input_value;
    }
}
